[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "clipboard-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
copypasta = { version = "0.10.2", features = [ "x11" ], default-features = false }

[profile.release]
lto = true
panic = "abort"
